### ISSUE TITLE
Undefined variable: filetype

### ISSUE THREAD

**Issue by pdobrescu** [PressLabs/autover#4]
Getting this Notice when accessing the Gitium/commits page:

PHP Notice:  Undefined variable: filetype in /www/wp-content/plugins/autover/autover.php on line 197 when calling autover_version_filter(), request: GET /wp-admin/admin.php?page=gitium/gitium-commits.php, request_id: b886268f9382083fbf7e23e2db1bef44

**Comment by zalmanu** [comment]
Please investigate further.

**Comment by Marius786** [comment]
Fixed by 007660e739cbb601604c6bbefbed24e592fefca1

**Comment by Marius786** [comment]
PHP Notice:  Undefined variable: filetype in /www/wp-content/plugins/autover/autover.php on line 59 when calling autover_version_filter()
