### ISSUE TITLE
Better explain the examples from the plugin page

### ISSUE THREAD

**Issue by pdobrescu** [PressLabs/autover#9]
We need to explain that 

`add_action('wp_enqueue_scripts','autover_add_style_and_script');` 

adds the scripts and styles to the frontend and 

`add_action('admin_enqueue_scripts','autover_add_style_and_script');` 

adds the scripts and styles to wp-admin.

Some users tend to simply copy paste the examples without checking the entire code and they end up with weird styles on wp-admin.

**Comment by zalmanu** [comment]
Needs checking (latest commits).
